n1 = float(input('Diga sua nota do 1º bimestre: '))
n2 = float(input('Diga sua nota do 2º bimestre: '))
n3 = float(input('Diga sua nota do 3º bimestre: '))
n4 = float(input('Diga sua nota do 4º bimestre: '))
print(f'A sua média anual é {(n1 + n2 + n3 + n4) / 4}')
